### ISSUE TITLE
[Question]Add plugin in appgyver Supersonic project

### ISSUE THREAD

**Issue by panalex1982** [bcsphere/bluetooth#44]
Hello, 
I am trying to use this plugin in supersonic project. I created correctly an custom scanner with plugin. 
But trying to use it I came up with those issue:
When I try to use any function properly with the BC object it throws TypeError exception. For example using BC.bluetooth.openBluetooth() throws "TypeError: Cannot read property 'openBluetooth' of undefined".

**Comment by DanTiana** [comment]
Hi, 
How is the situation? Please refer https://github.com/bcsphere/bcexplorer as the example.

**Comment by panalex1982** [comment]
Thanks for the example it is very helpful. I added an eventListener for the bcReady and I now I was able to use the BC object. 
However now every time a startScan a Classical device, and it finds a new one, then the application crashes showing the following error in my logcat:

```
10-19 16:22:57.998 26739-26846/? I/BCBluetooth: startClassicalScan
10-19 16:22:57.998 26739-26846/? D/AGWebView: Added plugin result to JS message queue: "OK"
10-19 16:22:58.008 6089-6200/? W/bt-btif: bta_dm_check_av:0
10-19 16:22:58.008 6089-6103/? I/BluetoothAdapterProperties: Callback:discoveryStateChangeCallback with state:1 disc: false
10-19 16:22:58.028 898-932/? I/ActivityManager: Start proc com.android.settings for broadcast 
com.android.settings/.bluetooth.BluetoothDiscoveryReceiver: pid=6807 uid=1000 gids={41000, 
3003, 1015, 1028, 3002, 3001, 3007, 1021, 3004, 3005, 1000, 3009, 1023}
10-19 16:22:58.088 26739-26739/? I/System.out: new classical bluetooth device 
found!00:11:67:BE:0C:B8
10-19 16:22:58.108 26739-26739/? D/AndroidRuntime: Shutting down VM
10-19 16:22:58.108 26739-26739/? W/dalvikvm: threadid=1: thread exiting with uncaught exception 
(group=0x4161e8b0)
------------------------->ERROR<-----------------
10-19 16:22:58.138 26739-26739/? E/AndroidRuntime: FATAL EXCEPTION: main
10-19 16:22:58.138 26739-26739/? E/AndroidRuntime: java.lang.RuntimeException: Error
receiving broadcast Intent { act=android.bluetooth.device.action.FOUND flg=0x10 (has extras) } in 
org.bcsphere.bluetooth.BCBluetooth$2@41acaeb0
```

And this is the script I wrote:
```javascript
$(function(){
  try{
    document.addEventListener('bcready', onBCReady, false);
    function onBCReady(){
        document.addEventListener('bluetoothstatechange', onBluetoothStateChange, false);
        BC.bluetooth.addEventListener("newdevice",addNewDevice);
        if(!BC.bluetooth.isopen){
          if(API !== "ios"){
            BC.Bluetooth.OpenBluetooth(function(){
              steroids.logger.log("open success!!");
            });
          }else{          
            alert("Please open your bluetooth first.");
          }
        }
      }


    function addNewDevice(s){
      alert(JSON.stringify(s));
      var newDevice = s.target;
      alert("new device be found! it's device Address is: " + newDevice.deviceAddress);
      alert(JSON.stringify(newDevice));     
    }


    function onBluetoothStateChange(){
        if(BC.bluetooth.isopen){
          alert('open');      
        }else{
          alert('close');
          BC.Bluetooth.OpenBluetooth(function(){
            alert("opened!");
          });
        }
      }
    }catch(e){
      alert("Bluetooth Enable Exception: "+e);
      steroids.logger.log("Bluetooth Enable Exception: "+e);
    } 
  });

  function startScan(){
    try{
      alert(111);     
      BC.Bluetooth.StartScan();      
    }catch(e){
      alert("Bluetooth Scan Exception: "+e);
      steroids.logger.log("Bluetooth Scan Exception: "+e);
    }
  }
```

**Comment by panalex1982** [comment]
Searching a little more about this issue I found that above error is triggered in the class BCBluetooth.java when the onReceive of the BroadcastReicever called. The problem is that newadvpacketContext object is null. Although in the logcat I can see that there is existing many references of that object. 
If that helps, the way I include the plugin is through the appgyver steroids build service using the {'source': 'https://github.com/bcsphere/bluetooth.git'} .

**Comment by DanTiana** [comment]
Is the issue related with a special model Android phone? thanks.

**Comment by panalex1982** [comment]
The android devices I use is the Sony Xperia SP(Jelly Bean 4.3) and the Samsung Galaxy Tab 2(Jelly Bean 4.1.2).

**Comment by DanTiana** [comment]
Android 4.1.2 is not supported. It will crash in that case.

**Comment by panalex1982** [comment]
As a conclusion I want to add that the problem is related with the way that appguiver build service, builds the application. Instead of using that build service I converted my application to use only cordova and that problem has fixed.
