### ISSUE TITLE
Cannot compile BCBluetooth.m

### ISSUE THREAD

**Issue by plaxdan** [bcsphere/bluetooth#45]
After a fresh install of the plugin with `cordova plugin add https://github.com/bcsphere/bluetooth.git` my Xcode project fails to build.

```
Cordova: 5.3.3
Xcode: 7.0.1
OSX: 10.11.1 Beta (15B38b)
```

![image](https://cloud.githubusercontent.com/assets/382348/10592855/2ccccdfa-767c-11e5-9211-bc06ff4b86c6.png)

**Comment by ErikAugust** [comment]
+1

**Comment by DanTiana** [comment]
Just updated to adapt to ios 9.1 change. Those API are deprecated. Please check.

**Comment by DanTiana** [comment]
The compilation error is fixed for xcode 7.0.1.

**Comment by plaxdan** [comment]
Thank you!
