### ISSUE TITLE
BC.bluetooth.isopen is always false on android 

### ISSUE THREAD

**Issue by jandureu** [bcsphere/bluetooth#49]
Hello

I'm testing your plugin and it's working good on an iPhone 6s.
But on an android phone Nexus 5, this value "BC.bluetooth.isopen" is always false, so I can't scan for new devices.

I have registered your code as a cordova plugin.
It seems that I never Go into this function:

```javascript
BC.bluetooth.getEnvironment(function(data){
				if(DEBUG){
					alert(JSON.stringify(data));
				}
				window.APPURL = window.location.href;
				window.DEVICEADDRESS = data.deviceAddress;
				window.API = data.api;
				window.VERSION = data.version;
				window.DEVICETYPE = data.deviceType;
				
				BC.bluetooth.getBluetoothState(function(arg){
					if(arg.state == "false"){
						BC.bluetooth.isopen = false;
					} else {
					    alert("PLUGIN   BC.bluetooth.isopen = true;");
						BC.bluetooth.isopen = true;
					}
					BC.Tools.FireDocumentEvent("bccoreready");
				},testFunc);
			},function(mes){alert(JSON.stringify(mes));});

```

**Comment by jandureu** [comment]
I found a little bit more about my problem  :
```javascript 
BC.bluetooth.getBluetoothState(function(arg){ ...} 
```
this function never responds on my android device so I never get into .isopen intialization.

**Comment by jandureu** [comment]
Sorry,it's working now.
I had a cache problem when deploying on android.

Is there something planned for a Windows 10 plugin ?

Thank you

**Comment by DanTiana** [comment]
Cool!
